### ISSUE TITLE
ERROR]: no implicit conversion of nil into String

### ISSUE THREAD

**Issue by universam1** [sparkleformation/sfn-bucketpurge#2]
Errors und doesnt clean the bucket:

```
[Sfn]: Callback after_config parameters_stacks: starting
[Sfn]: Callback after_config parameters_stacks: complete
[WARN]: Destroying Stack: o11n-eks-int-sam
[Sfn]: Callback before_destroy bucket_purge: starting
[ERROR]: no implicit conversion of nil into String
[DEBUG]: Stacktrace: TypeError: no implicit conversion of nil into String
/usr/local/bundle/gems/miasma-aws-0.3.30/lib/miasma/contrib/aws/storage.rb:164:in `join'
/usr/local/bundle/gems/miasma-aws-0.3.30/lib/miasma/contrib/aws/storage.rb:164:in `bucket_endpoint'
/usr/local/bundle/gems/miasma-aws-0.3.30/lib/miasma/contrib/aws/storage.rb:223:in `block in file_all'
/usr/local/bundle/gems/miasma-aws-0.3.30/lib/miasma/contrib/aws/storage.rb:34:in `all_result_pages'
/usr/local/bundle/gems/miasma-aws-0.3.30/lib/miasma/contrib/aws/storage.rb:219:in `file_all'
/usr/local/bundle/gems/miasma-0.3.8/lib/miasma/models/storage/files.rb:50:in `perform_population'
/usr/local/bundle/gems/miasma-0.3.8/lib/miasma/types/collection.rb:21:in `block in all'
/usr/local/bundle/gems/bogo-0.2.14/lib/bogo/memoization.rb:64:in `memoize'
/usr/local/bundle/gems/miasma-0.3.8/lib/miasma/types/collection.rb:20:in `all'
/usr/local/bundle/gems/sfn-bucketpurge-0.0.1/lib/sfn-bucketpurge/bucket_purge.rb:15:in `block in before_destroy'
/usr/local/bundle/gems/sfn-bucketpurge-0.0.1/lib/sfn-bucketpurge/bucket_purge.rb:8:in `each'
/usr/local/bundle/gems/sfn-bucketpurge-0.0.1/lib/sfn-bucketpurge/bucket_purge.rb:8:in `before_destroy'
/usr/local/bundle/gems/sfn-3.1.4/lib/sfn/command_module/callbacks.rb:45:in `call'
/usr/local/bundle/gems/sfn-3.1.4/lib/sfn/command_module/callbacks.rb:45:in `block in run_callbacks_for'
/usr/local/bundle/gems/sfn-3.1.4/lib/sfn/command_module/callbacks.rb:38:in `each'
/usr/local/bundle/gems/sfn-3.1.4/lib/sfn/command_module/callbacks.rb:38:in `run_callbacks_for'
/usr/local/bundle/gems/sfn-3.1.4/lib/sfn/command_module/callbacks.rb:17:in `api_action!'
/usr/local/bundle/gems/sfn-3.1.4/lib/sfn/command/destroy.rb:33:in `block in execute!'
/usr/local/bundle/gems/sfn-3.1.4/lib/sfn/command/destroy.rb:28:in `each'
/usr/local/bundle/gems/sfn-3.1.4/lib/sfn/command/destroy.rb:28:in `execute!'
/usr/local/bundle/gems/sfn-3.1.4/bin/sfn:52:in `block (4 levels) in <top (required)>'
/usr/local/bundle/gems/bogo-cli-0.2.18/lib/bogo-cli/setup.rb:26:in `block in bogo_cli_run'
/usr/local/bundle/gems/slop-3.6.0/lib/slop.rb:260:in `parse!'
/usr/local/bundle/gems/slop-3.6.0/lib/slop.rb:235:in `parse!'
/usr/local/bundle/gems/slop-3.6.0/lib/slop.rb:65:in `parse!'
/usr/local/bundle/gems/slop-3.6.0/lib/slop.rb:54:in `parse'
/usr/local/bundle/gems/bogo-cli-0.2.18/lib/bogo-cli/setup.rb:50:in `define'
/usr/local/bundle/gems/sfn-3.1.4/bin/sfn:14:in `<top (required)>'
/usr/local/bundle/bin/sfn:23:in `load'
/usr/local/bundle/bin/sfn:23:in `<top (required)>'
/usr/local/lib/ruby/2.6.0/bundler/cli/exec.rb:74:in `load'
/usr/local/lib/ruby/2.6.0/bundler/cli/exec.rb:74:in `kernel_load'
/usr/local/lib/ruby/2.6.0/bundler/cli/exec.rb:28:in `run'
/usr/local/lib/ruby/2.6.0/bundler/cli.rb:463:in `exec'
/usr/local/lib/ruby/2.6.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/lib/ruby/2.6.0/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/usr/local/lib/ruby/2.6.0/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/usr/local/lib/ruby/2.6.0/bundler/cli.rb:27:in `dispatch'
/usr/local/lib/ruby/2.6.0/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/usr/local/lib/ruby/2.6.0/bundler/cli.rb:18:in `start'
/usr/local/lib/ruby/gems/2.6.0/gems/bundler-1.17.2/exe/bundle:30:in `block in <top (required)>'
/usr/local/lib/ruby/2.6.0/bundler/friendly_errors.rb:124:in `with_friendly_errors'
/usr/local/lib/ruby/gems/2.6.0/gems/bundler-1.17.2/exe/bundle:22:in `<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'
exited with code 255
```
Any idea @chrisroberts ?

**Comment by flemingdp** [comment]
Interesting, I found I could reproduce this issue if I create a stack that has a bad bucket name in it. `bucket_one` is in create failed, so whole stack did not reach a successful creation state.

```
SparkleFormation.new(:bucket_test, :provider => :aws) do

  dynamic!(:bucket, :bucket_one) do
    depends_on 'Bucket2Bucket'
    properties do
      bucket_name 'Bad-bucketname2334'
    end
  end

  dynamic!(:bucket, :bucket2) do
    properties do
      bucket_name 'test122354'
    end
  end
end
```

Then when I goto run destroy with this callback enabled I get the error:
`[ERROR]: no implicit conversion of nil into String`
